web:
  build: .
  command: bash -c "npm run start"
  volumes:
    - .:/app
  working_dir: /app
  ports:
    - "3000:3000"
  environment:
    - PORT=3000
    - TWITTER_ACCESS_TOKEN=1301867773-sgQZoQjNFAW00QzaP3JV1UWK9PT0enzOwELKEqD
    - TWITTER_ACCESS_TOKEN_SECRET=CZCsHeLN1236gy36NXilIpN1dLfiaLEOIaauC693lKzFL
    - TWITTER_CONSUMER_KEY=2cIcz4mdLyKEtE3YScU5UQ
    - TWITTER_CONSUMER_SECRET=k89lpDyK0VkTLQm7KqCuL2UPiMpkhDhLmVzvJ9X3j4
